# Generated by Django 4.1.4 on 2023-01-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("source", "0005_sourceholding_balance_and_more"),
        ("spout", "0002_rename_created_at_spout_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spout",
            name="accepted",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spout",
            name="cache_body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="spout",
            name="sources",
            field=models.ManyToManyField(
                blank=True, related_name="spouts", to="source.source"
            ),
        ),
    ]
