version: '3.8'
services:
  database:
    image: postgres:13.2
    container_name: faucet-database
    restart: always
    environment:
      POSTGRES_USER: faucet
      POSTGRES_PASSWORD: faucet
      POSTGRES_DB: faucet
    volumes:
      - ./database:/var/lib/postgresql/data
    hostname: database
    ports:
      - 5432:5432
  api:
    container_name: faucet-api
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./:/code
    env_file:
      - ./.env
    ports:
      - 8000:8000
    restart: unless-stopped
    depends_on:
      - database
    links:
      - database
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        python manage.py runserver 0.0.0.0:8000
      "