# Generated by Django 4.2 on 2023-04-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='request_body',
            field=models.TextField(blank=True, help_text='This can be SQL to run on Flipside or a URL to submit a GET request to (must lead with `http`).', null=True),
        ),
        migrations.AddField(
            model_name='generator',
            name='request_type',
            field=models.CharField(choices=[('sql', 'SQL'), ('http', 'HTTP')], default='sql', max_length=255),
        ),
        migrations.AddField(
            model_name='generator',
            name='trigger',
            field=models.CharField(choices=[('* * * * *', 'Every Minute'), ('0 * * * *', 'Every Hour'), ('0 0 * * *', 'Every Day'), ('0 0 * * 0', 'Every Week'), ('0 0 1 * *', 'Every Month'), ('0 0 1 1 *', 'Every Year')], default='* * * * *', max_length=255),
        ),
    ]
