# Generated by Django 4.2 on 2023-04-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_generator_request_body_generator_request_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='response_column',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
