# Generated by Django 4.1.4 on 2023-01-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('source', '0005_sourceholding_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spout',
            fields=[
                ('token_id', models.IntegerField(primary_key=True, serialize=False)),
                ('units', models.IntegerField(default=0)),
                ('building', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sources', models.ManyToManyField(blank=True, null=True, related_name='spouts', to='source.source')),
            ],
        ),
    ]
