# Generated by Django 4.1.4 on 2023-01-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spout", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="spout", old_name="created_at", new_name="created",
        ),
        migrations.RenameField(
            model_name="spout", old_name="updated_at", new_name="updated",
        ),
        migrations.RemoveField(model_name="spout", name="building",),
        migrations.AddField(
            model_name="spout",
            name="built",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spout",
            name="looked",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spout",
            name="referrer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="spout",
            name="tail",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
