# Generated by Django 4.2 on 2023-04-19 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SourceIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('twitter_id', 'Twitter ID'), ('twitter_username', 'Twitter Username'), ('twitter_handle', 'Twitter Handle'), ('github_username', 'Github Username'), ('ens_name', 'ENS Name'), ('linkedin_username', 'LinkedIn Username'), ('discord_username', 'Discord Username'), ('reddit_username', 'Reddit Username'), ('telegram_username', 'Telegram Username'), ('email', 'Email'), ('lens_handle', 'Lens Handle')], max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='source.source')),
            ],
        ),
    ]
