# Generated by Django 4.1.4 on 2022-12-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SourceAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chain", models.CharField(blank=True, max_length=255, null=True)),
                ("contract", models.CharField(blank=True, max_length=255, null=True)),
                ("token_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "bucket",
                    models.CharField(
                        choices=[
                            ("nft", "NFT"),
                            ("defi", "Defi"),
                            ("social", "Social"),
                        ],
                        default="nft",
                        max_length=255,
                    ),
                ),
                (
                    "wallet_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "twitter_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "inspect_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "attributes",
                    models.ManyToManyField(blank=True, to="source.sourceattribute"),
                ),
            ],
        ),
    ]
