# Generated by Django 4.1.4 on 2022-12-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("source", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("twitter_id", "Twitter ID"),
                            ("twitter_username", "Twitter Username"),
                            ("twitter_handle", "Twitter Handle"),
                            ("github_username", "Github Username"),
                            ("ens_name", "ENS Name"),
                        ],
                        default="twitter",
                        max_length=255,
                    ),
                ),
                ("identifier", models.CharField(blank=True, max_length=255, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name="SourceAttribute",
            new_name="SourceHolding",
        ),
        migrations.RenameField(
            model_name="source",
            old_name="attributes",
            new_name="holdings",
        ),
        migrations.RemoveField(
            model_name="source",
            name="inspect_identifier",
        ),
        migrations.RemoveField(
            model_name="source",
            name="twitter_identifier",
        ),
        migrations.AddField(
            model_name="source",
            name="identifiers",
            field=models.ManyToManyField(blank=True, to="source.sourceidentifier"),
        ),
    ]
