# Generated by Django 4.1.4 on 2022-12-20 02:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("source", "0002_sourceidentifier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="sourceholding",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sourceholding",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="sourceidentifier",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("twitter_id", "Twitter ID"),
                    ("twitter_username", "Twitter Username"),
                    ("twitter_handle", "Twitter Handle"),
                    ("github_username", "Github Username"),
                    ("ens_name", "ENS Name"),
                    ("linkedin_username", "LinkedIn Username"),
                    ("discord_username", "Discord Username"),
                    ("reddit_username", "Reddit Username"),
                    ("email", "Email"),
                ],
                default="twitter",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="labels",
            field=models.ManyToManyField(blank=True, to="source.sourcelabel"),
        ),
    ]
