# Generated by Django 4.1.4 on 2022-12-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("source", "0004_remove_source_wallet_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourceholding",
            name="balance",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sourceidentifier",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("twitter_id", "Twitter ID"),
                    ("twitter_username", "Twitter Username"),
                    ("twitter_handle", "Twitter Handle"),
                    ("github_username", "Github Username"),
                    ("ens_name", "ENS Name"),
                    ("linkedin_username", "LinkedIn Username"),
                    ("discord_username", "Discord Username"),
                    ("reddit_username", "Reddit Username"),
                    ("telegram_username", "Telegram Username"),
                    ("email", "Email"),
                    ("lens_handle", "Lens Handle"),
                ],
                default="twitter",
                max_length=255,
            ),
        ),
    ]
